<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1PHE2Q8" failures="1" tests="3" name="Error Validation Test" time="53.414" errors="0" timestamp="2024-07-02T11:57:30 IST">
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="chkAgreeErrorValidation" time="14.556">
    <skipped/>
  </testcase> <!-- chkAgreeErrorValidation -->
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="chkAgreeErrorValidation" time="12.072">
    <failure type="java.lang.AssertionError" message="expected [Please accept Terms Conditions - Required] but found [Please accept Terms &amp;amp; Conditions - Required]">
      <![CDATA[java.lang.AssertionError: expected [Please accept Terms Conditions - Required] but found [Please accept Terms & Conditions - Required]
at rahulshettyacademy.ErrorValidationTest.chkAgreeErrorValidation(ErrorValidationTest.java:46)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- chkAgreeErrorValidation -->
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="productErrorValidation" time="6.721"/>
</testsuite> <!-- Error Validation Test -->
